# Generated by Django 6.0.3 on 2026-04-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_avatar_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavioralprofile',
            name='top_merchants',
            field=models.JSONField(default=list, help_text='List of most frequent merchant categories'),
        ),
        migrations.AlterField(
            model_name='behavioralprofile',
            name='typical_active_hours',
            field=models.JSONField(default=list, help_text='List of active hours e.g., [8, 9, 14, 20]'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='location',
            field=models.CharField(default='Lagos, NG', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant_category',
            field=models.CharField(default='transfer', max_length=100),
        ),
    ]
