# Generated by Django 6.0.3 on 2026-04-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavioralprofile',
            name='avg_transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='behavioralprofile',
            name='max_transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='behavioralprofile',
            name='top_merchants',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='fraudanalysis',
            name='fraud_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fraudanalysis',
            name='risk_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
