# Generated by Django 6.0.3 on 2026-04-15 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_behavioralprofile_avg_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='location',
        ),
        migrations.AlterField(
            model_name='behavioralprofile',
            name='typical_active_hours',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(default='system', max_length=20),
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(default='Production Key', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
